export const CONTACT_LIST = 'Contacts'
export const CONTACT_DETAIL = 'Contact details'
export const CREATE_CONTACT = 'Create contact'
export const SETTINGS = 'Settings'
export const LOGIN = 'Login'
export const SIGNUP = 'Signup'
export const HOME_NAVIGATOR = 'Home'
